"""
Django settings for toursSenderismo project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Configuraciones existentes
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8oq_e8x%8vpg)d3c(er5pq)c_r&gbbk(vm9)07ikgno4(6+**+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'comentarios',
    'inicio',
    'mensajeria',
    'pagos',
    'tours',
    'usuarios',

    
    
]
JAZZMIN_SETTINGS = {
      "site_title": "Administrador de Itzpapalotl Tours",
    "site_header": "Itzpapalotl Tours",
    "site_brand": "Itzpapalotl Tours",
    "site_logo": "Itzpapalotl",  # Texto que se mostrará como logo
    "welcome_sign": "Bienvenido a Itzpapalotl Tours",
    "copyright": "Itzpapalotl Tours",
    "user_avatar": None,
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "tours": "fas fa-hiking",
        "tours.tour": "fas fa-route",
        "pagos.pago": "fas fa-credit-card",
        "mensajeria.mensaje": "fas fa-envelope",
        "comentarios.comentario": "fas fa-comments",
    },

    "show_sidebar": False,
    "topmenu_links": [
    {"name": "Inicio", "url": "admin:index", "permissions": ["auth.view_user"]},
    
    {"model": "auth.User"},
    {
        "app": "tours",
        "name": "Tours",
        "permissions": ["tours.view_tour"],  # Agrega permisos específicos si es necesario
        "models": [
            {"name": "Lista de Tours", "url": "admin:tours_tour_changelist"},
            {"name": "Agregar Nuevo Tour", "url": "admin:tours_tour_add"},
            # Añade más modelos si es necesario
        ],
    },
    {
        "app": "pagos",
        "name": "Pagos",
        "permissions": ["pagos.view_pago"],  # Agrega permisos específicos si es necesario
        "models": [
            {"name": "Lista de Pagos", "url": "admin:pagos_pago_changelist"},
            {"name": "Agregar Nuevo Pago", "url": "admin:pagos_pago_add"},
            # Añade más modelos si es necesario
        ],
    },
    {
        "app": "mensajeria",
        "name": "Mensajería",
        "permissions": ["mensajeria.view_mensaje"],  # Agrega permisos específicos si es necesario
        "models": [
            {"name": "Bandeja de Entrada", "url": "admin:mensajeria_mensaje_changelist"},
            {"name": "Redactar Nuevo Mensaje", "url": "admin:mensajeria_mensaje_add"},
            # Añade más modelos si es necesario
        ],
    },
    {
        "app": "comentarios",
        "name": "Comentarios",
        "permissions": ["comentarios.view_comentario"],  # Agrega permisos específicos si es necesario
        "models": [
            {"name": "Lista de Comentarios", "url": "admin:comentarios_comentario_changelist"},
            {"name": "Agregar Nuevo Comentario", "url": "admin:comentarios_comentario_add"},
            # Añade más modelos si es necesario
        ],
    },
],

}



JAZZMIN_UI_TWEAKS = {
    "theme": "minty",  
}

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
)


LOGIN_URL = '/login/'  # URL de inicio de sesión
LOGOUT_URL = '/logout/'  # URL de cierre de sesión
LOGIN_REDIRECT_URL = '/'  # URL a la que se redirige después del inicio de sesión exitoso

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # Asegúrate de tener esto
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'toursSenderismo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'toursSenderismo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

'''DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}'''
DATABASES = {
'default': {
'ENGINE': 'django.db.backends.mysql',
'NAME': 'ejemplo',
'USER': 'root',
'PASSWORD':'1234',
'HOST': 'localhost',
'PORT': '3306',

    }
}
# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/


STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    BASE_DIR / "static",
    BASE_DIR / "inicio/static",
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "media")