# Generated by Django 4.2.13 on 2024-08-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_alter_reseña_rating_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='latitud',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='longitud',
            field=models.TextField(blank=True, null=True),
        ),
    ]
